name: Shared Reusable Smoke

on:
  workflow_call:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Shared reusable workflow is running
        run: echo "Shared reusable workflow is running"
